version: '3'

services:
  nestjs-boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    ports:
      - 5001:8080
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - nestjs-db
      - redis

  nestjs-db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_CONTAINER}
      MYSQL_PASSWORD: ${DB_PASSWORD_CONTAINER}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2-rc
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  node_modules:
  mysql-data:
  redis-data:
